var searchData=
[
  ['kudu_20c_2b_2b_20client_20api_20documentation',['Kudu C++ client API documentation',['../index.html',1,'']]],
  ['keepalive',['KeepAlive',['../classkudu_1_1client_1_1_kudu_scanner.html#aa4a0caf7142880255d7aac1d75f33d21',1,'kudu::client::KuduScanner']]],
  ['knotimestamp',['kNoTimestamp',['../classkudu_1_1client_1_1_kudu_client.html#a196f1a18c000cdca309d05161caaddaa',1,'kudu::client::KuduClient']]],
  ['kudu',['kudu',['../namespacekudu.html',1,'']]],
  ['kudu_5fcheck_5fok',['KUDU_CHECK_OK',['../status_8h.html#ac503ba85e942147294cdc82087da60f6',1,'status.h']]],
  ['kudu_5fcheck_5fok_5fprepend',['KUDU_CHECK_OK_PREPEND',['../status_8h.html#a706c9f6ef1715b8f7a9185fb3c247d3f',1,'status.h']]],
  ['kudu_5flog_5fand_5freturn',['KUDU_LOG_AND_RETURN',['../status_8h.html#abbd85cc2c5535627091bb06a21918150',1,'status.h']]],
  ['kudu_5freturn_5fnot_5fok',['KUDU_RETURN_NOT_OK',['../status_8h.html#a0de56a3f0e9d83b8ffdd63eac83c54ab',1,'status.h']]],
  ['kudu_5freturn_5fnot_5fok_5fprepend',['KUDU_RETURN_NOT_OK_PREPEND',['../status_8h.html#af66b8458f1d3f1264c1da86744e29e46',1,'status.h']]],
  ['kudu_5freturn_5fnot_5fok_5fret',['KUDU_RETURN_NOT_OK_RET',['../status_8h.html#a58d31c81bf1101a3ead737e9a4a4f223',1,'status.h']]],
  ['kudu_5fwarn_5fnot_5fok',['KUDU_WARN_NOT_OK',['../status_8h.html#a1e64fec5ef85c0c738f6ac3f398f607e',1,'status.h']]],
  ['kuduclient',['KuduClient',['../classkudu_1_1client_1_1_kudu_client.html',1,'kudu::client']]],
  ['kuduclientbuilder',['KuduClientBuilder',['../classkudu_1_1client_1_1_kudu_client_builder.html',1,'kudu::client']]],
  ['kuducolumnschema',['KuduColumnSchema',['../classkudu_1_1client_1_1_kudu_column_schema.html#a8cde78ce096e34e81b565da6a38aae2f',1,'kudu::client::KuduColumnSchema::KuduColumnSchema(const std::string &amp;name, DataType type, bool is_nullable=false, const void *default_value=NULL, KuduColumnStorageAttributes attributes=KuduColumnStorageAttributes())'],['../classkudu_1_1client_1_1_kudu_column_schema.html#afc82e98af83ba61079ba5d30401b5872',1,'kudu::client::KuduColumnSchema::KuduColumnSchema(const KuduColumnSchema &amp;other)']]],
  ['kuducolumnschema',['KuduColumnSchema',['../classkudu_1_1client_1_1_kudu_column_schema.html',1,'kudu::client']]],
  ['kuducolumnspec',['KuduColumnSpec',['../classkudu_1_1client_1_1_kudu_column_spec.html',1,'kudu::client']]],
  ['kuducolumnstorageattributes',['KuduColumnStorageAttributes',['../classkudu_1_1client_1_1_kudu_column_storage_attributes.html#a9bd5f6bce0a7369da5cd1f60341d1d71',1,'kudu::client::KuduColumnStorageAttributes']]],
  ['kuducolumnstorageattributes',['KuduColumnStorageAttributes',['../classkudu_1_1client_1_1_kudu_column_storage_attributes.html',1,'kudu::client']]],
  ['kududelete',['KuduDelete',['../classkudu_1_1client_1_1_kudu_delete.html',1,'kudu::client']]],
  ['kuduerror',['KuduError',['../classkudu_1_1client_1_1_kudu_error.html',1,'kudu::client']]],
  ['kuduinsert',['KuduInsert',['../classkudu_1_1client_1_1_kudu_insert.html',1,'kudu::client']]],
  ['kuduloggingcallback',['KuduLoggingCallback',['../classkudu_1_1client_1_1_kudu_logging_callback.html',1,'kudu::client']]],
  ['kuduloggingfunctioncallback',['KuduLoggingFunctionCallback',['../classkudu_1_1client_1_1_kudu_logging_function_callback.html#a4263c504b21e0e5827f47a902e908a2c',1,'kudu::client::KuduLoggingFunctionCallback']]],
  ['kuduloggingfunctioncallback',['KuduLoggingFunctionCallback',['../classkudu_1_1client_1_1_kudu_logging_function_callback.html',1,'kudu::client']]],
  ['kuduloggingfunctioncallback_3c_20void_20_2a_20_3e',['KuduLoggingFunctionCallback&lt; void * &gt;',['../classkudu_1_1client_1_1_kudu_logging_function_callback.html',1,'kudu::client']]],
  ['kuduloggingmembercallback',['KuduLoggingMemberCallback',['../classkudu_1_1client_1_1_kudu_logging_member_callback.html#aeda4119b1288db0d055c9800e3485fd8',1,'kudu::client::KuduLoggingMemberCallback']]],
  ['kuduloggingmembercallback',['KuduLoggingMemberCallback',['../classkudu_1_1client_1_1_kudu_logging_member_callback.html',1,'kudu::client']]],
  ['kudupartialrow',['KuduPartialRow',['../classkudu_1_1_kudu_partial_row.html#a4a628a93a6e65c176277f8f7bfa57f24',1,'kudu::KuduPartialRow::KuduPartialRow(const Schema *schema)'],['../classkudu_1_1_kudu_partial_row.html#aac9b016a50d2fd0bff9e65a15b145858',1,'kudu::KuduPartialRow::KuduPartialRow(const KuduPartialRow &amp;other)']]],
  ['kudupartialrow',['KuduPartialRow',['../classkudu_1_1_kudu_partial_row.html',1,'kudu']]],
  ['kudupredicate',['KuduPredicate',['../classkudu_1_1client_1_1_kudu_predicate.html',1,'kudu::client']]],
  ['kuduscanbatch',['KuduScanBatch',['../classkudu_1_1client_1_1_kudu_scan_batch.html',1,'kudu::client']]],
  ['kuduscanner',['KuduScanner',['../classkudu_1_1client_1_1_kudu_scanner.html',1,'kudu::client']]],
  ['kuduscanner',['KuduScanner',['../classkudu_1_1client_1_1_kudu_scanner.html#a2c621f778072a02f4092e96a0baf8180',1,'kudu::client::KuduScanner']]],
  ['kuduscantoken',['KuduScanToken',['../classkudu_1_1client_1_1_kudu_scan_token.html',1,'kudu::client']]],
  ['kuduscantokenbuilder',['KuduScanTokenBuilder',['../classkudu_1_1client_1_1_kudu_scan_token_builder.html',1,'kudu::client']]],
  ['kuduscantokenbuilder',['KuduScanTokenBuilder',['../classkudu_1_1client_1_1_kudu_scan_token_builder.html#aa8d300b560d419030abd503b66812484',1,'kudu::client::KuduScanTokenBuilder']]],
  ['kuduschema',['KuduSchema',['../classkudu_1_1client_1_1_kudu_schema.html#a41a683f3d93357fe68531bf71df39d02',1,'kudu::client::KuduSchema']]],
  ['kuduschema',['KuduSchema',['../classkudu_1_1client_1_1_kudu_schema.html',1,'kudu::client']]],
  ['kuduschemabuilder',['KuduSchemaBuilder',['../classkudu_1_1client_1_1_kudu_schema_builder.html',1,'kudu::client']]],
  ['kudusession',['KuduSession',['../classkudu_1_1client_1_1_kudu_session.html',1,'kudu::client']]],
  ['kudustatuscallback',['KuduStatusCallback',['../classkudu_1_1client_1_1_kudu_status_callback.html',1,'kudu::client']]],
  ['kudustatusfunctioncallback',['KuduStatusFunctionCallback',['../classkudu_1_1client_1_1_kudu_status_function_callback.html#aca289bbf6ad9720bd74a90550f6c9b3b',1,'kudu::client::KuduStatusFunctionCallback']]],
  ['kudustatusfunctioncallback',['KuduStatusFunctionCallback',['../classkudu_1_1client_1_1_kudu_status_function_callback.html',1,'kudu::client']]],
  ['kudustatusmembercallback',['KuduStatusMemberCallback',['../classkudu_1_1client_1_1_kudu_status_member_callback.html#acdb02b9798adf2c80b39cfb024f199aa',1,'kudu::client::KuduStatusMemberCallback']]],
  ['kudustatusmembercallback',['KuduStatusMemberCallback',['../classkudu_1_1client_1_1_kudu_status_member_callback.html',1,'kudu::client']]],
  ['kudutable',['KuduTable',['../classkudu_1_1client_1_1_kudu_table.html',1,'kudu::client']]],
  ['kudutablealterer',['KuduTableAlterer',['../classkudu_1_1client_1_1_kudu_table_alterer.html',1,'kudu::client']]],
  ['kudutablecreator',['KuduTableCreator',['../classkudu_1_1client_1_1_kudu_table_creator.html',1,'kudu::client']]],
  ['kudutabletserver',['KuduTabletServer',['../classkudu_1_1client_1_1_kudu_tablet_server.html',1,'kudu::client']]],
  ['kuduupdate',['KuduUpdate',['../classkudu_1_1client_1_1_kudu_update.html',1,'kudu::client']]],
  ['kuduupsert',['KuduUpsert',['../classkudu_1_1client_1_1_kudu_upsert.html',1,'kudu::client']]],
  ['kuduvalue',['KuduValue',['../classkudu_1_1client_1_1_kudu_value.html',1,'kudu::client']]],
  ['kuduwriteoperation',['KuduWriteOperation',['../classkudu_1_1client_1_1_kudu_write_operation.html',1,'kudu::client']]]
];
